language: node_js
node_js:
  - 10.12.0 # This version should be fully supported
  - 10
  - 12
  - 14
cache:
  npm: false
jobs:
  include:
    # Special case for older versions of Node.js that are not supported,
    # under which we do not want to run the entire test suite.
    - node_js:
      - 0.10
      - 0.12
      - 4
      - 6
      - 8
      - 10.11.0
      script: './bin/cmd.js'
